




name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "zuka-github"
  EB_APPLICATION_NAME       : "zukaapp"
  EB_ENVIRONMENT_NAME       : "Zukaapp-env"
  DEPLOY_PACKAGE_NAME       : "zukaa_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
       
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*






